### ISSUE TITLE
Migration issues tracking

### ISSUE THREAD

**Issue by simahawk** [OCA/oca-github-bot#101]
Proposal by @dreispt: "generating one issue per module to migrate with a "13.0-MIG" milestone, and then track the milestone?"

Original comment: https://github.com/OCA/stock-logistics-reporting/issues/92#issuecomment-589751416

Ongoing PR to make current issues update automatically: https://github.com/OCA/oca-github-bot/pull/97

CC @dreispt @sbidoul @pedrobaeza

**Comment by pedrobaeza** [comment]
As said, I don't like this: https://github.com/OCA/stock-logistics-reporting/issues/92#issuecomment-590198580

**Comment by sbidoul** [comment]
I personally like the idea of individual issues, for the simplicity and ease of cross-referencing using native GitHub features. I'd use a label instead of a milestone though.

**Comment by pedrobaeza** [comment]
Seriously 40 opened issue per version in repos like OCA/web? Please don't go that direction...

**Comment by dreispt** [comment]
@sbidoul or maybe a tag + a milestone?: [Migration] +[13.0]

I would be good to hear more opinion on the Issue per Branch vs Issue per Module.

My personally feeling is that the single issue is redundant (additional overhead) with a list of Issues, that would be automatically updated as they are being solved.

Having dozens or hundreds of issues and PRs is something we are already living with.
![image](https://user-images.githubusercontent.com/1246629/75144683-5adfa480-56ef-11ea-8d0d-ccf14aca63b4.png)

**Comment by legalsylvain** [comment]
Can be closed.
It seems we now have an issue per revision created by the bot. (Like https://github.com/OCA/pos/issues/543)

By the way, agree with @pedrobaeza regarding the design per version and not by module.
