### ISSUE TITLE
[RFC] Adding changelog mechanism

### ISSUE THREAD

**Issue by legalsylvain** [OCA/oca-github-bot#104]
Hi all,

I begin to use this tools for GRAP repositories. I was thinking to implement a new feature, to handle changelog. Something like : 

**command proposal**

```
\ocabot merge minor changelog
* Changelog Text line 1
* changelog Text line 2
* ...
```

**algorithm proposal**

if changelog option is present :
 
- check if version changed. (by command minor / major / patch or manually). --> Error / ignore otherwise.
- check if README folder exists --> Error / ignore otherwise.
- Create ``HISTORY.rst`` file inside, if not exists.
- Add the changelog text on the top of the file file ``HISTORY.rst`` and a title section with ``#[VERSION] [MERGE_DATE]``
- Call ``oca-gen-addon-readme``
- etc...

**Not sure**
- Do we have to block, if no changelog command are set, and HISTORY.rst is present ?
It could prevent to have inconsistent description, like [this one](https://github.com/OCA/account-financial-reporting/tree/12.0/account_financial_report#changelog). 
   - History file mentions V11
   - The code is for V12.
- How to handle if a PR concerns many modules ? Use same changelog text for all the impacted modules ? 

Thanks for your comments.
regards.

**Comment by sbidoul** [comment]
For changelogs, there was also this https://github.com/OCA/maintainer-tools/pull/432.

**Comment by legalsylvain** [comment]
how. That's true. (and I commented that PR ...)
Sorry for the noice.
