### ISSUE TITLE
Check module name availability on apps.odoo.com

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#120]
When a PR that adds new addons is opened, check apps.odoo.com and odoo-community.org/apps to verify if the new addons name are available.

From https://github.com/OCA/web/pull/1602#issuecomment-638689627

**Comment by legalsylvain** [comment]
Thanks for reporting : 

2 remarks : 
- I think we should check if the module exist in any available version. AFAIK, if a PR propose a module for 12.0 serie named ``xxx`` and a module exists in the appstore named ``xxx`` for another serie like 10.0 for exemple, the existing module will block the possibility to have the OCA module available;
- anybody know how to call the odoo appstore via api ? I don't found where is the code used by odoo for its appstore. not sure it's public. it could be a mess to have to parse the HTML.

algorithm proposal : 
- call Odoo appstore ; check if module exists in any revision. If yes, check if website is OCA current website. If not, raise a warning;
- call OCA appstore : check if module exist in any revision. if yes, and if repository is not the same, raise a warning.

**Comment by pedrobaeza** [comment]
There's simply no API.

**Comment by legalsylvain** [comment]
Closing. supersed by #149. (to do).
