### ISSUE TITLE
CLA bot on translation commits

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#14]
@gurneyalex if you look at this PR: https://github.com/OCA/account-analytic/pull/204, you can see that there are commits made by "Harald Panten" that come from Weblate, but they are considered as CLA unknown.

First question: should we force to sign a CLA for translations?

If so, @sbidoul / @max3903 , we have to try to enforce that CLA in Weblate login or translation request.

In any case, I think CLA bot should ignore that commits.

**Comment by gurneyalex** [comment]
I don't think we want to enforce a CLA for translations. 

Do we have a proper way of checking for translation commits ? The commit message starting with "Translated using Weblate" ? This looks a bit week to me...

**Comment by pedrobaeza** [comment]
I'm afraid there's no other way to know them...

**Comment by gurneyalex** [comment]
I'll work on this today

**Comment by gurneyalex** [comment]
PR submitted #21

**Comment by gurneyalex** [comment]
fix deployed on runbot
