### ISSUE TITLE
[Question] version of maintainer-tools

### ISSUE THREAD

**Issue by legalsylvain** [OCA/oca-github-bot#148]
Hi. 

I'm trying to update my bot, to test & use the latest PR. 

i just checked that the version of the tools ``maintainer-tools`` is very obsolete. The version is pinned here : 
https://github.com/OCA/oca-github-bot/blob/master/Dockerfile#L29 

This is from May 2020. Is there any reason not to use the branch head?

**Comment by sbidoul** [comment]
It is very important to pin oca-gen-addon-readme, as any change to it, even minor, triggers a regeneration of *all* README.rst files. For OCA at least, we need to create separate virtualenvs in the Dockerfile, to we can have different versions of the maintainer-tools tools.

There might be a better strategy for (re)-generating these README.rst files, but for now this is it.

**Comment by legalsylvain** [comment]
OK. Thanks for your answer ! 

So, it is not dangerous that I use the head version for my little grap bot.
