### ISSUE TITLE
The bot is not merging now

### ISSUE THREAD

**Issue by Yajo** [OCA/oca-github-bot#152]
Something must have failed in the last deployment; the bot is not merging.

Here you can see that I issued the merge command, the bot created the branch, it finished in green, but it didn't merge it. I repeated, and the same: https://github.com/OCA/event/pull/231#issuecomment-898281311

cc @sbidoul

**Comment by legalsylvain** [comment]
Are you sure, there is a message on your PR : 

```
@Yajo The merge process could not start, because command `git merge --no-ff -m Merge PR #231 into 13.0

Signed-off-by Yajo tmp-pr-231` failed with output:

CONFLICT (add/add): Merge conflict in website_event_questions_free_text/README.rst
Auto-merging website_event_questions_free_text/README.rst
Automatic merge failed; fix conflicts and then commit the result.

```

**Comment by legalsylvain** [comment]
FYI, I just merged a PR on OCA/pos
all seems OK.

https://github.com/OCA/pos/pull/700

**Comment by Yajo** [comment]
> there is a message on your PR

That message was posted after I manually merged the PR and conflicts happened, but not before (see the timeline).

**Comment by legalsylvain** [comment]
yes, but if the message is displayed, it means the bot was still working. Don't you think ?

**Comment by sbidoul** [comment]
The most probable explanation is that the status webhooks were triggered while the bot was restarting, and GitHub retried them a little bit later. So yes, everything operating normally as far as I can tell.
