### ISSUE TITLE
ocabot sometimes not merging some PRs

### ISSUE THREAD

**Issue by nilshamerlinck** [OCA/oca-github-bot#164]
In the last weeks, I noticed that the ocabot sometimes doesn't fully complete merge tasks, for no valid reason: i.e.
- despite pre-commit and travis checks being green on the merge branch, see for example https://github.com/OCA/field-service/pull/859 
- not even creating the merge branch, and without any other explicit message error, see for example: https://github.com/OCA/intrastat-extrastat/pull/154

Trying again (eventually twice) is enough for the task to finally go through, see for example: https://github.com/OCA/bank-payment/pull/866

I'm not familiar enough with the ocabot code to make any hypothesis. Does somebody have an idea what could explain this irregular behavior?

**Comment by pedrobaeza** [comment]
This has happened due to GitHub expiring token due to a secret reveal. It should be fixed with #163.
