### ISSUE TITLE
Maintainer notification is broken ?

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#166]
## Describe the bug

I think I have seen somwhere that the the notification of maintainers when there is a new PR on their modules is not working anymore.
Is that correct ?

**Comment by pedrobaeza** [comment]
Yes, I haven seen it since a lot, but I remember you deactivate it somehow being very hammering.

**Comment by sbidoul** [comment]
What I deactivated is the call for maintainers when there is no declared maintainers because of #153.

**Comment by pedrobaeza** [comment]
Then I don't know what is the reason, but it seems it's not working.

**Comment by sbidoul** [comment]
This was mentioned [here](https://github.com/OCA/reporting-engine/pull/552#issuecomment-985309401) by @LoisRForgeFlow
