### ISSUE TITLE
Merging PR should mark a line in the "Migration to version xx" issue as done.

### ISSUE THREAD

**Issue by legalsylvain** [OCA/oca-github-bot#189]
Ref : talk [here](https://github.com/OCA/OpenUpgrade/issues/3288#issuecomment-1157007829) with @pedrobaeza 

**Event** : on pull_request / merged

**Action** : 
1. check in all the comments of the PR if one contains the order ``/ocabot migration yyy``
2. if yes, find the issue named "Migration to version xx"
3. if found, find the line name "``- [ ] yyy`` - By @xxx - PR ref"
4. if found replace "``- [ ]``" by "``- [x]``"

Regarding step 1, I think it's going to be a little heavy to do that, but I don't see any alternative to identify the yyy (module name).

Comments welcome.

**Comment by pedrobaeza** [comment]
Instead of 1, I think it's better to just go to the migration issue of the target branch, and look for a line with the PR number. If found, mark it if not already done.

**Comment by legalsylvain** [comment]
> Instead of 1, I think it's better to just go to the migration issue of the target branch, and look for a line with the PR number. If found, mark it if not already done.

:100: Indeed ! Thanks.
