### ISSUE TITLE
[FIX] wrong link in the message sent by oca-clabot

### ISSUE THREAD

**Issue by tafaRU** [OCA/oca-github-bot#208]
The message sent  by **oca-clabot** contains a wrong link: https://odoo-community.org/page/cla
See https://github.com/OCA/l10n-italy/pull/2948#issuecomment-1251298851 as an example.

**Expected behavior**
The link should be replaced by https://odoo-community.org/about/cla

**Comment by legalsylvain** [comment]
Hi, thanks for reporting. Could you make a PR ? 

thanks !

**Comment by sbidoul** [comment]
Hm, that is weird. Summoning @gdgellatly to see if it is intended that the cla page is now at /about/cla instead of /page/cla, because there is already a redirect in place to /page/cla.

**Comment by gdgellatly** [comment]
@sbidoul I did put in redirects for all pages I moved. Must have missed that one but have now added. The correct page is now /about/cla

**Comment by tafaRU** [comment]
I close then in the face of https://github.com/OCA/oca-github-bot/issues/208#issuecomment-1253418536.
