### ISSUE TITLE
ocabot merge: Protected branch update failed for

### ISSUE THREAD

**Issue by hparfr** [OCA/oca-github-bot#210]
On [Field-service](https://github.com/OCA/field-service/) repo, `ocabot merge` fails:
for instance:  https://github.com/OCA/field-service/pull/957

`@hparfr The merge process could not be finalized, because command git push origin 14.0-ocabot-merge-pr-957-by-hparfr-bump-minor:14.0 failed with output:

remote: error: GH006: Protected branch update failed for refs/heads/14.0.        
remote: error: Changes must be made through a pull request.        
To https://github.com/OCA/field-service
 ! [remote rejected]   14.0-ocabot-merge-pr-957-by-hparfr-bump-minor -> 14.0 (protected branch hook declined)
error: failed to push some refs to 'https://***@github.com/OCA/field-service'
`

Any ideas ?

**Comment by legalsylvain** [comment]
I had the same problem on a GRAP repo. 
AFAIK, protected branch is impatible with oca-bot.
solution 1 : unprotect the main branches
solution 2 : propose a patch in oca-bot with an alternative git command. (I'm not sure it's possible though)
