### ISSUE TITLE
[RFC] generate README.rst in ocabot merge only

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#223]
Currently, the readme generator is runs
1. in ocabot merge
2. in the main branch actions that run nightly

Due to 2, whenever we change the readme generator, it causes a mass commit and publishing to PyPI for all addons.
To avoid that, we have refrained from deploying readme generator updates.

One approach I had in mind is https://github.com/OCA/maintainer-tools/issues/520. I.e. embedding into the generated readme a hash of the fragments and regenerate only if the fragments have changed.

An alternative that might be easier could be to stop generating the readmes nightly, and generate them only on ocabot merge.

**Comment by pedrobaeza** [comment]
Wasn't the idea behind nightly update to get all the massive changes at once?

**Comment by sbidoul** [comment]
Well yes, but generating all these commits on 200 repos x 8 branches is killing the CI, and publishing 12 000 packages to PyPI at once is... well.

And the benefit of updating everything is marginal.

**Comment by pedrobaeza** [comment]
Well, I'm missing the new runboat link instead of the redirection in all READMEs, specially as it requires the runbot_ids.txt file (and I found the problem on new OCA/spreadsheet repo). But if you think it's better to not do it, let's deactivate it.

**Comment by legalsylvain** [comment]
I 'm in favor to simply disable the nightly regeneration. 

- dont see the interest to have the very latest version of readme. "On each merge" is enough. 
- it adds a new weird file. we'll have to explain its role to all the contributors. People that don't understand will remove it when porting module, etc...
- the hash will change when changing readme fragments, that can maybe generate extra git conflicts when cherry picking many commits (port, etc)

If in any moment, the template change is very important we can enable it again temporarly to apply the changes.

**Comment by sbidoul** [comment]
I'm going to close this because I think we should rely less on the ocabot merge command than more.
It's nice and all but at some point, maybe native GitHub features can do the job (automerge, etc).

And in older large repos that have become red and unfixable for reasons, manual merges remain sometimes useful.
