### ISSUE TITLE
Not needed POT updates

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#227]
Look at this POT update commit:

https://github.com/OCA/l10n-spain/commit/6a2ab188198bcd4bbbb1c7c00a0b05ca7ae77167

It's not changing anything valuable, but it requires another CI to be launched, provoking commit noise and delay on the merges.

Can this be avoided?

**Comment by sbidoul** [comment]
This is not the right project for this issue. It might be click-odoo-contrib or, more likely, Odoo itself, or the library it uses to generate pot files.

**Comment by pedrobaeza** [comment]
I don't know who generates it, but do you agree it's a problem?

**Comment by sbidoul** [comment]
Not sure. Where do these two lines it is removing come from?

**Comment by pedrobaeza** [comment]
I launched the ocabot command for merging in https://github.com/OCA/l10n-spain/pull/2574, and on the merge branch, such commit was added. I suppose that the bot launches POT+PO update in some moment.

**Comment by sbidoul** [comment]
Was due to en.po being present. So closing.
