### ISSUE TITLE
The bot is slow to respond

### ISSUE THREAD

**Issue by yajo** [OCA/oca-github-bot#235]
**Is your feature request related to a problem?**
Lately I'm noticing a big lag on our dear bot. Here you have a few cases where its response took a really long time. You can check the response timestamps from github comments:
- https://github.com/OCA/partner-contact/pull/1505#issuecomment-1517328759
- https://github.com/OCA/crm/pull/488#issuecomment-1521290780
- https://github.com/OCA/stock-logistics-reporting/pull/273#issuecomment-1495411803
- https://github.com/OCA/web/pull/2357#pullrequestreview-1405294178 (this has not responded yet at the time of writing)

**Describe the solution you'd like**
I don't know if this is just randomness or there's some kind of problem, but I hope it can be investigated and fixed if needed.

**Additional context**
Related: https://github.com/OCA/oca-github-bot/issues/234

**Comment by sbidoul** [comment]
I don't think there is an issue with the bot itself. GitHub webhook delivery issues or perf issues on the oca server are the most common causes od delays.

**Comment by sbidoul** [comment]
Closing this as there is nothing to do in this repo. A hardware upgrade will eventually happen.
