### ISSUE TITLE
CLA bot: Hammering of CLA missing message

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#29]
When there's a missing GitHub login, the message is repeated again and again with each commit:

![seleccion_066](https://user-images.githubusercontent.com/7165771/49640367-b865d380-fa0d-11e8-9feb-e8c245a22e77.png)

Can we make this to be put only once?

Reference PR: https://github.com/OCA/account-closing/pull/88

**Comment by gurneyalex** [comment]
for the record, I'm working on this

**Comment by pedrobaeza** [comment]
Thanks!

**Comment by gurneyalex** [comment]
closing. please reopen if the fix is not working correctly
