### ISSUE TITLE
merge bot: Abort CI on pull request branch?

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#46]
Should merge bot abort the CIs on PRs branches for avoiding double load? Observed case: I have put the command in https://github.com/OCA/OpenUpgrade/pull/1740, and see that another CI has been triggered on the new branch https://github.com/OCA/OpenUpgrade/commits/ocabot-merge-pr-1740-to-12.0-by-pedrobaeza-bump-no, so I have canceled the one in pull request. The status there is red now, but we have saved one heavy Travis job.

**Comment by sbidoul** [comment]
I'm not sure there are two jobs? I don't think the bot restarts travis jobs on the PR. However the job created on the bot branch may be visible on the PR. But there is only one job.

**Comment by pedrobaeza** [comment]
In the observed PR, there were 2 jobs. I suppose it depends if there are extra commits or not due to README + POT + etc.

**Comment by sbidoul** [comment]
Strange it looks like you cancelled the one that was running on the `ocabot-merge-` branch.
Ping me if you notice another case like this.

**Comment by sbidoul** [comment]
Closing for now. Reopen if needed.
