### ISSUE TITLE
setup bot: setup folder incorrectly added in OpenUpgrade project

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#47]
You can see it in https://github.com/OCA/OpenUpgrade/commit/52d51a169d0d2c8c6e98f1f4e3656d4a8778beb7#diff-1315e10d504fa040f404ce6d71a01b34

**Comment by sbidoul** [comment]
Hm I did not really expect the merge bot to be used on projects that are not regular addons repos.

**Comment by pedrobaeza** [comment]
Well, we have OCB + OpenUpgrade that are susceptible o be used with.
