### ISSUE TITLE
Repo addons table generator

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/oca-github-bot#48]
I don't know if there is already a way to get a list of all the modules in the OCA repositories (with its version and the latest update date), but if it doesn't exist I believe that would be very helpful.

There are more than 150 repositories in OCA, mostly with branches for Odoo 12.0, 11.0, 10.0... Each branch can have several modules, and each module can have several versions and updates. So, keep the trace of all that modules are a hard and tedious work

I don't know if there are already any plan to get a list of all the modules, or something like that. But maybe that github-bot could help to create and update that list.

Would it be useful to have a table with all the OCA modules? And sorting or filtering that modules by repository, Odoo version, last update?

**Comment by sbidoul** [comment]
The bot already populates and add-ons table in the README.md of each repo
if a specific placeholder is present. Unfortunately that placeholder got
lost in most 11 and 12 branches.

As for a global list you should find https://odoo-community.org/apps useful.

**Comment by pedrobaeza** [comment]
I removed them when we switched to empty new branches, as now all the directories are migrated modules, and this table was adding a lot of noise in commits, specially when bumping version.

I think what @emagdalenaC2i asks about is our app "store" that you have mentioned (https://odoo-community.org/apps).

**Comment by emagdalenaC2i** [comment]
Actually that app store is useful if you are looking for specific modules, but there are no information of the module version or the last update, so it is not very helpful if you want to follow the development of OCA modules.

I was thinking of a way to improve the monitoring of the development of the OCA modules. Not only to be able to detect the new modules that may be interesting, but also to have a report of the new versions with improvements and bug fixes of the modules that are being used.

**Comment by emagdalenaC2i** [comment]
I'm taking a look at those tables and actually it's very close to what I was looking for. 

@pedrobaeza Are there any chance to reactivate them?

**Comment by sbidoul** [comment]
One one need to re-insert the placeholder for the table in README.md. I'm personally in favor of it but I have other priorities for now.

I'm closing this here as it is not related to the bot which is functioning normally.
