### ISSUE TITLE
merge bot: parse command inside a greater message

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#53]
For now, the merge bot only reacts to the merge command putting that comment in an isolated message (example of greater message: https://github.com/OCA/account-invoicing/pull/552#issuecomment-507203903).

**Comment by sbidoul** [comment]
#49 is tracking the handling of approval comments and can be handled independently.

**Comment by pedrobaeza** [comment]
Right, I didn't remember I already put that one. Renaming the issue.
