### ISSUE TITLE
mention declared maintainers when a new PR is open on their addons

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#63]
When a new PR is open, add an @ comment to mention declared maintainers of modified addons.

**Comment by pedrobaeza** [comment]
Shouldn't they be assigned instead?

**Comment by sbidoul** [comment]
I'd rather let the maintainer assign it him/herself, because we don't want to give the impression the maintainer is expected to be the first/only one to review. Although it certainly must have an important word to say on all PRs towards his/her modules.

**Comment by sbidoul** [comment]
Done in #77
