### ISSUE TITLE
merge bot: multiple version bumping is not working?

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#64]
On https://github.com/OCA/purchase-workflow/pull/733#issuecomment-520704025, I have instructed the bot to bump patch version, but it seems it doesn't do it:

https://github.com/OCA/purchase-workflow/commits/12.0-ocabot-merge-pr-733-by-pedrobaeza-bump-patch

**Comment by sbidoul** [comment]
Bumping version is done after tests on the merge bot branch. What is more strange is that the branch is green and the bot does not seem to process it.

**Comment by pedrobaeza** [comment]
Should I put again the command?

**Comment by sbidoul** [comment]
There was a GitHub connection error: https://sentry.odoo-community.org/oca/oca-github-bot/issues/1200/

Yes please retry the command.

**Comment by pedrobaeza** [comment]
Indeed the bump is done later.
