### ISSUE TITLE
push readme and setup.py to PR branches

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#66]
When the contributor leaves it's branch open to changes by maintainers, it would be nice to have the bot push the README update and setup.py generation to the PR branch.

**Comment by sbidoul** [comment]
An alternative approach is to include that in the pre-commit configuration.

**Comment by legalsylvain** [comment]
Readme and setup are now included in pre-commit.
@sbidoul : can be closed, I think.
