### ISSUE TITLE
merge strategies

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#68]
Currently, the default and only available merge strategy for the merge command is `rebase`.

After further reflection, I now think the default merge strategy could be `merge`.
We can create the merge bot branch by branching off the target branch and merging the PR into it. The rest of the process can be identical and we keep the same benefits (i.e. testing on top of the main branch before merging into it, bumping version as last operation, etc). 

Additional benefits of the merge strategy would be that branches which contain merge conflict resolution should be mergeable via the bot command, and GitHub would see PRs as merged.

Other merge stragegies (rebase with autosquash, squash all) can be made available via additional options to the ocabot merge command.

**Comment by pedrobaeza** [comment]
When one merge operation for solving conflicts has been used, at the end, this will arise on next version when fetching commit history, so I prefer to not delay that and fix it directly in the PR.

**Comment by hbrunn** [comment]
I'm pro merge commits because the rebasing strips GPG signatures
