### ISSUE TITLE
Using black

### ISSUE THREAD

**Issue by legalsylvain** [OCA/oca-github-bot#74]
Hi all,

some people are talking about using black for the OCA. 
https://twitter.com/SBidoul/status/1176422992613711872 by @sbidoul 

How to go ahead ? 
1) are they people against that proposal ? 

2) if not, I guess that black should be integrated in oca bot, to blackify automaticaly all the new PR.
what do you think ? 

kind regards.

CC : @sebastienbeau, @jgrandguillaume

**Comment by pedrobaeza** [comment]
Let's talk about it at OCA days

**Comment by sbidoul** [comment]
Indeed we can talk about it at #OCDdays. That said, the bot will not be involved in this. If it is decided to use Black, it should be checked by travis. And this is best done using [pre-commit](https://pre-commit.com/). An example can be found in the [storage](https://github.com/OCA/storage/blob/12.0/.pre-commit-config.yaml) repository.

**Comment by sbidoul** [comment]
An issue to track this is good to have, though. Could you open one in [mqt](https://github.com/oca/maintainer-quality-tools/issues)?
