### ISSUE TITLE
Ignore /ocabot commands of quoted text

### ISSUE THREAD

**Issue by SimoRubi** [OCA/oca-github-bot#82]
Quoting a comment that contains an ocabot command triggers the bot, but it should not.
See https://github.com/OCA/bank-payment/pull/622#issuecomment-538881553

**Comment by pedrobaeza** [comment]
Well, I think this is going to be more difficult to be detected, but it depends on the regexp. It's not usual to quote that part any way...

**Comment by SimoRubi** [comment]
> It's not usual to quote that part any way...

Right, but I am used to the 'Quote reply' function of github and it quotes the whole comment.
I don't think that oca-bot being triggered is the expected behavior.

**Comment by pedrobaeza** [comment]
@sbidoul do you see it feasible?

**Comment by pedrobaeza** [comment]
@SimoRubi can you try?

**Comment by sbidoul** [comment]
Which makes me think we probably want some command to abort a merge. Because if an addon maintainer would have done that by accident he would have had no way to cancel it.

**Comment by pedrobaeza** [comment]
Current method is to delete the created branch, but yes, it's will be useful.

**Comment by lreficent** [comment]
cancelling travis build does also work.

**Comment by SimoRubi** [comment]
look like this is solved: https://github.com/OCA/oca-github-bot/pull/84#issuecomment-543330554, thanks!
