### ISSUE TITLE
Add nobump option to ocabot merge

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#90]
We tend to see maintainers doing ocabot merge without bumping version (patch|minor|major), simply because they forget or don't know it's possible. 

In the current OCA workflow, bumping version is the most common operation.

I therefore propose to change the ocabot merge command to *require* (patch|minor|major|nobump), so the action to take in that regard is explicit and we don't have a default that does not do what we want most of the time.

**Comment by lmignon** [comment]
:+1:

**Comment by pedrobaeza** [comment]
OK for me too including the nobump option for avoiding undesired changes if for example manual version is provided for migration scripts.

**Comment by kittiu** [comment]
:+1:
