### ISSUE TITLE
Adopt an addon campaign

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#93]
Following https://odoo-community.org/groups/contributors-15/contributors-150608?mode=thread&date_begin=&date_end=

See also #88

**Comment by luisg123v** [comment]
What would I need to adopt a module? Just submit a PR adding myself as maintainer?

**Comment by sbidoul** [comment]
> What would I need to adopt a module? Just submit a PR adding myself as maintainer?

@luisg123v yes exactly, and then make sure you perform [maintainer duties](https://odoo-community.org/page/maintainer-role).

**Comment by legalsylvain** [comment]
I'm not sure to understand the workflow you propose. 
I have this one in my mind : 
- oca-github-bot scan all the repositories, and all the branches
- when he see some unmaintained modules, he opens an issue, pinging author(s) ?

**Comment by sbidoul** [comment]
> workflow you propose

I imagine the bot commenting on new pull requests that touch addons without declared maintainers.

**Comment by ivantodorovich** [comment]
To close, since https://github.com/OCA/oca-github-bot/pull/130 and https://github.com/OCA/oca-github-bot/pull/139 are merged?
