### ISSUE TITLE
Ocabot merge should not trigger Runbot builds

### ISSUE THREAD

**Issue by dreispt** [OCA/oca-github-bot#94]
These Runbot build are not necessary and avoiding them would spare precious Runbot resources.

**Comment by pedrobaeza** [comment]
Yes, AFAIK, runbot result is being ignored, so I agree in principle, but not sure if it can be avoided. We have the module installed if I'm not wrong, but putting the `[ci skip]` in the commit message will avoid also Travis and it will affect the final merge as well.

**Comment by dreispt** [comment]
I guess we can't use `[ci skip]` because Ocabot needs a green build to continue, right?
So maybe we need a specific marker, like `[runbot skip]`, and somehow have Runbot understand it.

**Comment by pedrobaeza** [comment]
But there's the second cons: it won't build the definitive runbot once merged.

**Comment by dreispt** [comment]
Good point Pedro.
We should keep the build.
