### ISSUE TITLE
maintainer not allowed to merge in 13.0 branches?

### ISSUE THREAD

**Issue by lreficent** [OCA/oca-github-bot#95]
See https://github.com/OCA/server-ux/pull/111#issuecomment-561554729.

I am not maintainer in server-ux and I've been merging some base_tier_validation PR lately (e.g: https://github.com/OCA/server-ux/pull/105#issuecomment-558119878). Now in the v13 migration PR I can't.

**Comment by pedrobaeza** [comment]
The problem is that the maintainer role is being added in the PR. This is not allowed as everyone will be able to create a PR adding him/her as maintainer and self-merging it. This is difficult to handle I'm afraid...

**Comment by lreficent** [comment]
I see, and it is hard to check the maintainer in a previous branch. Well, then let's close this as it is a "know issue".

btw, Can you merge that PR? :wink:

**Comment by pedrobaeza** [comment]
Yeah, let's see what @sbidoul thinks. The only way I see right now is to come back to approach where new branches started from what was on previous one and putting everything as installable: False, but I don't like that approach due to a lot of cons.

**Comment by sbidoul** [comment]
I share @pedrobaeza's analysis.

**Comment by lreficent** [comment]
Yes, I also agree. Thanks for the quick answers :1st_place_medal:
