### ISSUE TITLE
Generate requirements.txt

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#98]
The repo-level `requirements.txt` could be generated from addons external dependencies.

Benefits:
- ensure the quality of external dependencies declarations in addons
- less redundant manual work to maintain this file

Drawbacks
- in a transition period, this will reveal a lot of repos where external dependencies are not declared properly

**Comment by simahawk** [comment]
@sbidoul nice idea. I wonder if we can do the same with oca_dependencies.txt.
It's a bit more complex but not impossible I think.
The only issue I see is: how can we specify temporary overrides for PR?
Maybe w/ a specific file like `oca_dependencies_override.txt`?

**Comment by sbidoul** [comment]
We could get rid of `oca_dependencies.txt` if travis would install dependencies with pip. There is an old PR of mine that was doing just this: https://github.com/OCA/maintainer-quality-tools/pull/343
Temporary overrides can be done by updating requirements.txt with a git branch requirement.

**Comment by sbidoul** [comment]
FTR, adding `MQT_DEP=PIP` now enables an alternate installation of addons to test and their dependencies, using the dependencies recorded in manifests (and possibly refined with version constraints in setup.py). This method does not use `requirements.txt` nor `oca_dependencies.txt`.

**Comment by legalsylvain** [comment]
> FTR, adding MQT_DEP=PIP now enables an alternate installation of addons to test and their dependencies, using the dependencies recorded in manifests (and possibly refined with version constraints in setup.py). This method does not use requirements.txt nor oca_dependencies.txt.

if travis doesn't requires ``requirements.txt`` nor ``oca_dependencies.txt``, this issue will be obsolete ?

Do you know how runbot works ? is it also based on there two files ?

**Comment by sbidoul** [comment]
> if travis doesn't requires requirements.txt nor oca_dependencies.txt, this issue will be obsolete ?

Yes

> Do you know how runbot works ? is it also based on there two files ?

I *think* OCA's runbot generates a docker image from travis.yml using https://github.com/vauxoo/travis2docker. So if it works in travis it should work in runbot too. In reality there are probably edge cases but I guess these are fixable.

**Comment by sbidoul** [comment]
So let's close this, we have a better path forward.
