### ISSUE TITLE
Twitter Message from @OCA_Bot

### ISSUE THREAD

**Issue by jcdrubay** [OCA/oca-github-bot#99]
Hi,

I am not sure if it is here that this issue should be posted, I apologize if I make a mistake... feel free to let me know where I should post this.

I see the following twitter message

> It's #OCA #Odoo review day. PR's https://t.co/HOCgq1Za4C Guide https://t.co/CKOtgWriNO Waffle https://t.co/fiqrdX0Qmt IRC irc://freenode/OCA

But it seems that Waffle link is dead.

Also, I could not connect to the IRC channel. Is it me (I am an IRC newbie) or is it outdated?

**Comment by sbidoul** [comment]
@jcdrubay this is actually a bit embarassing... it looks like that OCA Bot twitter account has escaped his master and nobody really knows where those tweet come from.

**Comment by simahawk** [comment]
it should be fixed by @gdgellatly .
Let's see on the next bot round.
